version: '3.8'

services:
  symfony6-database:
    container_name: symfony6-mysql
    # we use the default mysql docker image with the default configuration
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_symfony6_db
      MYSQL_USER: app_symfony6_user
      MYSQL_PASSWORD: symfony6
    # expose port 3306 so we can connect to the server with desktop applications like MySQL Workbench
    ports:
      - '3306:3306'
    volumes:
      # create a local volume for the database storage so you won't loose the data if you delete the docker container
      - ./db_data:/var/lib/mysql
      - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.conf
      # load the sql files from here on database creation
      # - ./mysql/:/docker-entrypoint-initdb.d/
    networks:
        - app_symfony6
  symfony6-php:
    container_name: symfony6-php
    # we build our own docker image with custom configurations
    build:
      dockerfile: ./php/Dockerfile
      context: "."
    volumes:
      - ./app:/var/www/app_symfony6
    depends_on:
      - symfony6-database
    # environment:
    #   PHP_OPCACHE_ENABLE: 0
    networks:
      - app_symfony6
  symfony6-nginx:
    container_name: symfony6-nginx
    build:
      dockerfile: ./nginx/Dockerfile
      context: "."
    ports:
      - 8080:80
      - 443:443
    volumes:
      - ./app:/var/www/app_symfony6
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/certs/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - symfony6-php
      - symfony6-database
    networks:
      - app_symfony6
  symfony6-phpmyadmin:
    container_name: symfony6-pma
    depends_on:
      - symfony6-database
    image: phpmyadmin:latest
    # open http://localhost:8080 in your browser to access phpmyadmin console
    ports:
      - '8081:80'
    # load environment variables necessary to create the connection to the database container
    env_file:
      - ./mysql/phpmyadmin.env
    restart: always
    networks:
      - app_symfony6
  symfony6-adminer:
    container_name: symfony6-adminer
    depends_on:
      - symfony6-database
    image: adminer
    restart: always
    ports:
      - 8082:8080
  symfony6-mailer:
    container_name: symfony6-mailer
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    restart: always
networks:
    app_symfony6:
      name: app_symfony6